### ISSUE TITLE
batch requests

### ISSUE THREAD

**Issue by oldashes** [robertmryan/AFHTTPSessionOperation#5]
Hi, thank you for your great job! 
But i encountered a problem that the method `bacthOfRequests:` has been delete when i updated the AFNetworking 3.0 .

I read your code , maybe your `SessionOperation` can help me, Could you make some suggests for me ? 

Thank you!

**Comment by robertmryan** [comment]
Yes, `batchOfRequestOperations` was retired, and yes, you can achieve similar functionality using this operation subclass because this enjoys all of the `NSOperation` features. Thus, if you want notification when all the requests are done, you can do that using operation dependencies, for example:

``` objc
NSOperation *completionOperation = [NSBlockOperation blockOperationWithBlock:^{
    NSLog(@"all done");
}];

AFHTTPSessionManager *manager = [AFHTTPSessionManager manager];
manager.responseSerializer = [AFImageResponseSerializer serializer];

NSOperationQueue *queue = [[NSOperationQueue alloc] init];
queue.maxConcurrentOperationCount = 3;

NSArray *filenames = @[@"file1.jpg", @"file2.jpg", @"file3.jpg", @"file4.jpg", @"file5.jpg", @"file6.jpg"];

for (NSString *filename in filenames)  {
    NSString *urlString = [@"http://example.com" stringByAppendingPathComponent:filename];
    NSOperation *operation = [AFHTTPSessionOperation operationWithManager:manager HTTPMethod:@"GET" URLString:urlString parameters:nil uploadProgress:nil downloadProgress:^(NSProgress *downloadProgress) {
        NSLog(@"%@: %.1f", filename, downloadProgress.fractionCompleted * 100.0);
    } success:^(NSURLSessionDataTask *task, id responseObject) {
        NSLog(@"%@: %@", filename, NSStringFromCGSize([responseObject size]));
    } failure:^(NSURLSessionDataTask *task, NSError *error) {
        NSLog(@"%@: %@", filename, error.localizedDescription);
    }];
    [completionOperation addDependency:operation];
    [queue addOperation:operation];
}

[[NSOperationQueue mainQueue] addOperation:completionOperation];
```

Or you can monitor the progress of the individual downloads in aggregate using `NSProgress`, like shown in the Swift example on the [README page](https://github.com/robertmryan/AFHTTPSessionOperation/blob/master/README.md). There are tons of options.
